#include <iostream>

using namespace std;

/*--------------- infix, prefix, postfix -> [in Simple Words] -----------------*/

// They Are The [NOTATIONS] or [WAY] To The Write The Expressions...

// 1: In-Fix -> "Simple Mathematical EXpressions"; eg. a+b, a-b, p/q etc...
// 2: Pre-Fix -> "Simple Mathematical EXpressions"; eg. +ab, -ab, /pq etc...
// 3: Post-Fix -> "Simple Mathematical EXpressions"; eg. ab+, ab-, pq/ etc...
